### ISSUE TITLE
Resolution incorrect while using custom resolutions.

### ISSUE THREAD

**Issue by Possibly-Pos** [JulianChow94/Windows-screenFetch#16]
Display is 1366x768 but custom set to 1932x1086. Screenfetch shows 1280x1024. It picks it up wrong even once changed back to the real resolution of the monitor.

Another edit gave it a go in powershell instead of ming and this showed up. Seems to pickup my Disk drive.
https://i.imgur.com/GGg70Y1.png

**Comment by JulianChow94** [comment]
Theres been a couple of fixes merged in to the codebase but I have yet to update the package on PSGallery. Once I do that I can revist this.
