### ISSUE TITLE
[Suggestion] Windows 7 logo/distro argument

### ISSUE THREAD

**Issue by Kleadron** [JulianChow94/Windows-screenFetch#17]
It's possible to install the Windows Management Framework 5.1 on Windows 7 and that lets you run screenfetch, but the logo is out of place. Is there a chance you could put the Windows 7 logo in the art?

**Comment by JulianChow94** [comment]
Do you have a screenshot of the logo out of place? I'm not putting a Windows 7 logo would necessarily fix it

**Comment by pocc** [comment]
It's been 5 months since this issue was touched and the initial poster has not provided additional details. I recommend that the maintainers close this issue due to inactivity.
