### ISSUE TITLE
Command doesn't run

### ISSUE THREAD

**Issue by HRTHXC** [JulianChow94/Windows-screenFetch#18]
Installed with "Install-Module -Name windows-screenfetch", no error given, attempting to run with screenfetch or windows-screenfetch. No good.

![image](https://user-images.githubusercontent.com/24234044/47277122-7a594f80-d619-11e8-99c6-68d0ca078630.png)

**Comment by JulianChow94** [comment]
Could you navigate to your modules folder and see if it exists there?

**Comment by JulianChow94** [comment]
This is what I get when I try to install it, are you sure you didn't reject it as a Trusted Repository?
Would help if you provided a screenshot of your installation command as well.

![image](https://user-images.githubusercontent.com/5642774/47525954-7709d200-d86c-11e8-8f16-9386632578d0.png)

**Comment by pocc** [comment]
It's been 5 months since this issue was touched and the initial poster has not provided additional details. I recommend that the maintainers close this issue.
