### ISSUE TITLE
Better Ascii art

### ISSUE THREAD

**Issue by DRSDavidSoft** [JulianChow94/Windows-screenFetch#21]
### `screenfetch` on Cygwin uses this:

<img width="600" alt="scrf-w10" src="https://user-images.githubusercontent.com/4673812/53051237-93331e00-34b0-11e9-9429-d588ec2aa572.png">

```
                                  .., 
                      ....,,:;+ccllll 
        ...,,+:;  cllllllllllllllllll 
  ,cclllllllllll  lllllllllllllllllll 
  llllllllllllll  lllllllllllllllllll 
  llllllllllllll  lllllllllllllllllll 
  llllllllllllll  lllllllllllllllllll 
  llllllllllllll  lllllllllllllllllll 
  llllllllllllll  lllllllllllllllllll 
                                      
  llllllllllllll  lllllllllllllllllll 
  llllllllllllll  lllllllllllllllllll 
  llllllllllllll  lllllllllllllllllll 
  llllllllllllll  lllllllllllllllllll
  llllllllllllll  lllllllllllllllllll
  `'ccllllllllll  lllllllllllllllllll
         `'""*::  :ccllllllllllllllll
                        ````''"*::cll
                                   ``
```

### `Windows-screenFetch` uses this:
<img width="569" alt="wscrf" src="https://user-images.githubusercontent.com/4673812/53051373-fcb32c80-34b0-11e9-998e-a44273b43d30.png">

```
                         ....::::
                 ....::::::::::::
        ....:::: ::::::::::::::::
....:::::::::::: ::::::::::::::::
:::::::::::::::: ::::::::::::::::
:::::::::::::::: ::::::::::::::::
:::::::::::::::: ::::::::::::::::
:::::::::::::::: ::::::::::::::::
................ ................
:::::::::::::::: ::::::::::::::::
:::::::::::::::: ::::::::::::::::
:::::::::::::::: ::::::::::::::::
'''':::::::::::: ::::::::::::::::
        '''':::: ::::::::::::::::
                 ''''::::::::::::
                         ''''::::
                                 
```

I think the first one looks better. If you also agree, I'd appreciate updating the ascii art :)
Also, thanks for creating this awesome powershell tool 👍

**Comment by Tommasov** [comment]
Hello, what kind of terminal is the second one? I see some blur in the background.. really cool!

**Comment by DRSDavidSoft** [comment]
@Tommasov Oh, it's [FluentTerminal](https://github.com/felixse/FluentTerminal) created by @felixse, and I'm additionally running [Cmder](https://github.com/cmderdev/cmder)'s shell in it.

You can find a guide to install both here:
https://github.com/cmderdev/cmder/wiki/Seamless-FluentTerminal-Integration

---

P.S. If you like the blurred-behind effects, you can also check this PR for VS Code editor:
https://github.com/Microsoft/vscode/pull/52707
