### ISSUE TITLE
System Specs occupies more lines than the Ascii Art resource selected

### ISSUE THREAD

**Issue by Tvde1** [JulianChow94/Windows-screenFetch#25]
When I run `Screenfetch` I get this:
![image](https://user-images.githubusercontent.com/11540531/57765031-f70e6100-7704-11e9-9234-839dbb0a8123.png)

Probably because I have a bunch of network drives which make the text too long. Is showing this exception useful?

**Comment by lucknaumann** [comment]
Still occurring with version 1.0.3
