### ISSUE TITLE
cant do the match on 3TB drives

### ISSUE THREAD

**Issue by lukkan99** [JulianChow94/Windows-screenFetch#26]
![image](https://user-images.githubusercontent.com/7603446/58273572-456cd100-7d91-11e9-9362-cc8c3fd319d2.png)

**Comment by Tommasov** [comment]
That's a strange bug. Why is there a space between 2 and 794?

**Comment by lukkan99** [comment]
> That's a strange bug. Why is there a space between 2 and 794?

idk new powershell. this newst windows update. may 2019

**Comment by Cvolton** [comment]
i can confirm this bug, the space is most likely related to regional formatting (thousands separator)
