### ISSUE TITLE
Wont run on PowerShell Core as Get-WmiObject has been depreciated

### ISSUE THREAD

**Issue by ArnavD74** [JulianChow94/Windows-screenFetch#34]
PS version: v7.1.0-preview.2, found on https://github.com/PowerShell/PowerShell/releases
output: https://imgur.com/a/cwAhd85
source: PowerShell/PowerShell#4766

**Comment by mutageneral** [comment]
I think it should have been fixed with this: https://github.com/JulianChow94/Windows-screenFetch/pull/20

**Comment by ArnavD74** [comment]
Yup, got it by fetching the latest data.ps1, setting execution policy, and importing the module locally. For some reason, using Install-Module for screenfetch still gave me an older version that used Get-Wmi.
