### ISSUE TITLE
Runtime exception (division by zero), if the computer has a CD/DVD drive.

### ISSUE THREAD

**Issue by StanawalkaWorld** [JulianChow94/Windows-screenFetch#39]
Executing screenfetch on a computer with CD/DVD drive raises a Runtime exception (division by zero).

![error](https://user-images.githubusercontent.com/20837730/83506457-8250c500-a4c7-11ea-8c58-51ea0ec7b6ea.png)

Screenshot taken on Windows Terminal, but looks the same on a normal powershell

**Comment by davidpack** [comment]
I am having the same issue.
![broken screenfetch](https://user-images.githubusercontent.com/6349195/83696962-bdd4b780-a5cb-11ea-8af3-4efa6e53bf0a.jpg)

**Comment by TyNguyen2001** [comment]
![image](https://user-images.githubusercontent.com/64082226/83994105-9f7e0b80-a97f-11ea-931e-bed9c3c9919e.png)

**Comment by bburt91** [comment]
Same error, but no CD drive.

![fff](https://user-images.githubusercontent.com/54790276/84532775-6eb61300-acac-11ea-8223-2e68f54d81ae.png)

**Comment by uhgringow** [comment]
Same error, but no CD drive. 😟 

![Screenshot_1](https://user-images.githubusercontent.com/16261065/89375299-c4fb6d00-d6c3-11ea-95c0-8d6901515cc7.png)

**Comment by Adriiii** [comment]
From what I've understood from the source code, the issue has been patch but this version isn't distributed for yet.

**Comment by Adriiii** [comment]
Ok, I found a fix,
just download the repo from git
![image](https://user-images.githubusercontent.com/47462845/91971511-9cde4880-ed19-11ea-8a95-69c29573cf08.png)
(green button)

If you download it as a zip file, unzip it

Then go in it and copy the file named "Data.psm1"
![image](https://user-images.githubusercontent.com/47462845/91971786-0cecce80-ed1a-11ea-9b92-fe7114886be2.png)

Then you can go to the whatever folder address ist write in the error message
![image](https://user-images.githubusercontent.com/47462845/91972316-cfd50c00-ed1a-11ea-8575-58f4972fd7fd.png)
(In this example it's "C:\Program Files\WindowsPowerShell\Modules\windows-screenfetch\1.0.2\")

/!\ Be careful to not copy what's after the last "\"

![image](https://user-images.githubusercontent.com/47462845/91972713-5c7fca00-ed1b-11ea-9fc7-19f76463b5b2.png)

Now you can rename the Data.psm1 here to something like "Data.psm1.old" (it doesn't really matter, it's just to be able to find it back if the operation fails)

And you can finally Paste the Data.psm1 file that you copied earlier.

Now you just have to restart your shell and the error should disappear!


(I hope my French's English didn't bother you too much 😅)
