### ISSUE TITLE
Wrong information for disks

### ISSUE THREAD

**Issue by Akumatic** [JulianChow94/Windows-screenFetch#4]
I have 5 Drives (C, D, E, F, G), 2 Network Drives (P and S) and 1 DVD Drive (H).

![2017-09-23_12-16-09](https://user-images.githubusercontent.com/32218926/30772442-5d52d216-a05b-11e7-8977-2d2d5df92171.png)

- DVD-Drive H: is in the list, has 0GB/0GB and 51% used storage. Because of the empty space and dividing through zero the script throws exceptions at Line 152 and 156 of SystemInfoCollector.psm1:
```
+         $FreeDiskPercent = ($FreeDiskSizeGB / $DiskSizeGB) * 100;
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], RuntimeException
    + FullyQualifiedErrorId : RuntimeException
```
```
+         $UsedDiskPercent = ($UsedDiskSizeGB / $DiskSizeGB) * 100;
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], RuntimeException
    + FullyQualifiedErrorId : RuntimeException
```
- Disk D and E have both negative amount of used space and a negative usage percentage
- only one of the two Network Drives is listed
- the following exception is thrown in screenfetch.ps1:
```
System Specs occupies more lines than the Ascii Art resource selected
In Zeile:1 Zeichen:1
+ screenfetch
+ ~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,screenfetch.ps1
```

**Comment by JulianChow94** [comment]
Thanks for pointing this out, will address shortly

**Comment by cjpbirkbeck** [comment]
I have also encountered the divide by 0 error. It occurs with removable drives when nothing inserted with in them. They are listed in Win32_LogicalDisk but the values are null.

The fix is easy enough: if the drive size is null, set all the drives size to null; otherwise, calculate the drive space. Alternatively, you could have a message saying 'Drive is empty' or something to that effect.

**Comment by Akumatic** [comment]
> the exception thrown refers to having too many drives and the specification take up too many lines.

Is this a hard limit of the bash or just a problem with this program? It seems like the lines are stopping after the 3 additional empty lines of the windows ascii art, so i guess you could fix it easily. (see my next point)

>At this point I am considering showing only the default (C) drive, other drives could be shown through command line parameters.

Maybe you could check if the number of lines of system information is bigger  than the number of lines of ascii art and add aditional empty lines if necessary. 
By the way, the mac art has one more empty line than the windows art

> Would you mind posting the correct specifications for your disks so I can easily test them (Especially drive H)?

which specifications do you need? 

- C is a Crucial MX200 [250GB]
- D is a Toshiba DT01ABA300 [3000GB]
- E is a WD Blue WD20EZRZ [2000GB]
- F is a Seagate ST500DM002 [500GB]
- G is a Seagate ST3320820AS [320GB]
- H is a Samsung SH-222BB [DVD]

> The fix is easy enough: if the drive size is null, set all the drives size to null; otherwise, calculate the drive space. Alternatively, you could have a message saying 'Drive is empty' or something to that effect.

or you could ignore the drive at all if size = 0 and dont even list it.

**Comment by JulianChow94** [comment]
> Is this a hard limit of the bash or just a problem with this program? It seems like the lines are stopping after the 3 additional empty lines of the windows ascii art, so i guess you could fix it easily. (see my next point)

Currently it compares the # of lines of the specs vs the # of lines the ASCII art takes. You're right though, we can dynamically append lines to the art.

> or you could ignore the drive at all if size = 0 and dont even list it.
This seems most logical to me

**Comment by JulianChow94** [comment]
Closing since #7 has been merged

**Comment by e-cloud** [comment]
@JulianChow94 It's broken again. Coz by a new condition added and not covered with empty check.

```
所在位置 C:\Users\msi\Documents\WindowsPowerShell\Modules\windows-screenfetch\1.0.2\Data.psm1:174 字符: 13
+             $FreeDiskPercent = ($FreeDiskSizeGB / $DiskSizeGB) * 100;
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], RuntimeException
    + FullyQualifiedErrorId : RuntimeException
```

version: 1.0.2

**Comment by TeeJayD** [comment]
Issue still happens on the last version
 Disk C: 54GB / 111GB (49%)
Disk D: 773GB / 932GB (83%)
Disk E: -150,603GB / 1.397GB (-10.780%)
Disk F: 343GB / 466GB (74%)
Disk G: 44GB / 466GB (9%)
Disk H: 392GB / 447GB (88%)
Disk I: 0GB / 0GB (88%)

**Comment by NotNite** [comment]
Still happening for me.

**Comment by BKDOnions** [comment]
Folks Ive fixed the problems by copying extra lines in `Art.psm1` which locates in `$PSHome\Modules\windows-screenfetch` (you should this module folder by urselves, this might different bcuz the install methods, but most commonly for me is this) ![example](https://imgur.com/jVOF3Al.png) just like this

**Comment by BKDOnions** [comment]
You have to try and adjust @Akumatic @e-cloud @JulianChow94 @cjpbirkbeck (Sorry the pic above is misleading, that is not the String should ends)

**Comment by seojunaprk** [comment]
is that screenfetch for windows!?!?!?
