### ISSUE TITLE
Improve Performance

### ISSUE THREAD

**Issue by tracker1** [JulianChow94/Windows-screenFetch#56]
Not sure if, or how difficult it would be to improve performance, but this command seems to take 8+ seconds.  Where I'm able to use neofetch at the end of my WSL/Linux bashrc to display with each prompt, I cannot reasonably do this with powershell or git bash as it just takes too long to run.

**Comment by mmahacek** [comment]
I had submitted https://github.com/JulianChow94/Windows-screenFetch/pull/42 to improve performance by skipping pulling stats on network drives.  I had found this was taking up a good chunk of processing time on my system.
