### ISSUE TITLE
Wrong screen resolution

### ISSUE THREAD

**Issue by ghost** [JulianChow94/Windows-screenFetch#6]
My monitor has Full HD resolution, but the script does not detect it correctly. I'm running it on Windows 10 1709 (16299.64). I tried to execute the script with the usual privileges and on behalf of the administrator, this does not change the situation. What can be done about this?
<img width="960" alt="3" src="https://user-images.githubusercontent.com/20227986/34069978-0da753dc-e26d-11e7-9614-ac9197130624.png">

**Comment by JulianChow94** [comment]
Hey @ghost, whats displayed right now is the **effective** screen resolution, since you're running 1920 x 1080 on a 150% scaling, you're effectively running a resolution scaled to 1280 x 720p

This is by all means intended, but if it bothers a lot of people I am open to discussing changes

**Comment by halars** [comment]
I think it is misleading. Perhaps it is better to provide an additional field, "DPI scaling"?

**Comment by halars** [comment]
@ghost, you could change the following:
```
$resolution = [System.Tuple]::Create($monitor.Bounds.Width, $monitor.Bounds.Height);
$displayString = $resolution.Item1.ToString() + "x" + $resolution.Item2.ToString() + " ";
```
to
```
$video = Get-WmiObject -class "Win32_VideoController";
$displayString = $video.CurrentHorizontalResolution.ToString() + "x" + $video.CurrentVerticalResolution.ToString() + " ";
```
in "SystemInfoCollector.psm1"

**Comment by JulianChow94** [comment]
@halars Yeah i agree, I'll apply a change soon via a PR

**Comment by JulianChow94** [comment]
This has been resolved
