### ISSUE TITLE
Get my fork for better performance (shameless plug)

### ISSUE THREAD

**Issue by piotrpdev** [JulianChow94/Windows-screenFetch#73]
This repo seems abandoned, check out [my fork](https://github.com/piotrpdev/Windows-screenFetch-fast) to get 15x the performance and a PowerShell module with the latest commits.

You can also just install it if you want:
```pwsh
Install-Module -Name windows-screenfetch-fast
```

> You will have to uninstall the original since both use `screenfetch`: `Uninstall-Module -Name windows-screenfetch`

**Comment by lucknaumann** [comment]
_**Finally**_!

**Comment by JulianChow94** [comment]
Hey this is nice! @piotrpdev 

I'm getting back into things, I love some of the stuff you've done, I have a branch that re-organizes things up a bit coming up but if you'd like to make a PR once I'm done I'd love to merge your stuff and credit you if you're okay with that.

**Comment by piotrpdev** [comment]
> Hey this is nice! @piotrpdev
> 
> I'm getting back into things, I love some of the stuff you've done, I have a branch that re-organizes things up a bit coming up but if you'd like to make a PR once I'm done I'd love to merge your stuff and credit you if you're okay with that.

Thank you, I'd actually recommend https://github.com/AkariiinMKII/Windows-screenFetch instead 😅 I found his fork a bit after making mine and I think it is even better @AkariiinMKII

**Comment by JulianChow94** [comment]
Sounds good I'll reach out!
