### ISSUE TITLE
Attempted to divide by zero

### ISSUE THREAD

**Issue by FinnTheHero** [JulianChow94/Windows-screenFetch#75]
when I run screenfetch it displays one extra disk and gives error that it attempted to divide by zero.
![image](https://github.com/JulianChow94/Windows-screenFetch/assets/127041443/8c98f691-8582-4b5c-bfbc-33d1d1019fca)
my guess is that it's trying to display optical drive as a disk.

**Comment by FinnTheHero** [comment]
Added -1 on line 162 in for loop and this seems to be working.
![image](https://github.com/JulianChow94/Windows-screenFetch/assets/127041443/bd3dad73-85b3-483b-a328-293325449af7)
However, it didn't work when I added another disk cuz drive letter was F while optical drive had E. 
So, I changed optical drive letter to Z so it will always be placed as last, and it can now read other disks that I have added.
![image](https://github.com/JulianChow94/Windows-screenFetch/assets/127041443/ac5e58c8-4d29-461a-8960-3e37439deb1e)

**Comment by AkariiinMKII** [comment]
Hi, sorry for disturbing but would you mind testing how [this fork](https://github.com/AkariiinMKII/Windows-screenFetch) works with a optical drive?

**Comment by FinnTheHero** [comment]
It's working! 
![image](https://github.com/JulianChow94/Windows-screenFetch/assets/127041443/a4fd5038-6257-4978-9ebf-639a070f2c6b)

**Comment by AkariiinMKII** [comment]
> It's working! ![image](https://user-images.githubusercontent.com/127041443/266849412-a4fd5038-6257-4978-9ebf-639a070f2c6b.png)

Great! thanks a lot!
